# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core app to Azure Function App - MehrFarUserAccountService

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          $fullPath = "$env:AZURE_FUNCTIONAPP_PACKAGE_PATH/UserService"
          Write-Host "Full path = $fullPath"
          Get-ChildItem -Path $fullPath
          Push-Location $fullPath
          dotnet build --configuration Release --output ./output
          Pop-Location
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'MehrFarUserAccountService'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/UserService/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3C42C2CD4DE9431BBB1B82977CA8CEBC }}
